[package]
name = "zerojudge-testcase-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
eyre = "0.6.12"
itertools = "0.14.0"
json5 = "0.4.1"
once_cell = "1.20.3"
ordered-float = "5.0.0"
rand = { version = "0.9.0", features = ["os_rng"] }
rand_chacha = { version = "0.9.0", features = ["os_rng"] }
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
